/* Automatically @generated by tree-sitter v0.25.6 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 16
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 22
#define ALIAS_COUNT 0
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_spdx_license_identifier_token1 = 1,
  sym_license_identifier = 2,
  anon_sym_pragma = 3,
  anon_sym_SEMI = 4,
  anon_sym_CARET = 5,
  anon_sym_TILDE = 6,
  anon_sym_GT_EQ = 7,
  anon_sym_LT_EQ = 8,
  anon_sym_GT = 9,
  anon_sym_LT = 10,
  anon_sym_EQ = 11,
  sym_version_literal = 12,
  sym_identifier = 13,
  sym_source_file = 14,
  sym__top_level_element = 15,
  sym_spdx_license_identifier = 16,
  sym_pragma_directive = 17,
  aux_sym__pragma_expression = 18,
  sym_version_constraint = 19,
  sym_version_operator = 20,
  aux_sym_source_file_repeat1 = 21,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_spdx_license_identifier_token1] = "spdx_license_identifier_token1",
  [sym_license_identifier] = "license_identifier",
  [anon_sym_pragma] = "pragma",
  [anon_sym_SEMI] = ";",
  [anon_sym_CARET] = "^",
  [anon_sym_TILDE] = "~",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT] = ">",
  [anon_sym_LT] = "<",
  [anon_sym_EQ] = "=",
  [sym_version_literal] = "version_literal",
  [sym_identifier] = "identifier",
  [sym_source_file] = "source_file",
  [sym__top_level_element] = "_top_level_element",
  [sym_spdx_license_identifier] = "spdx_license_identifier",
  [sym_pragma_directive] = "pragma_directive",
  [aux_sym__pragma_expression] = "_pragma_expression",
  [sym_version_constraint] = "version_constraint",
  [sym_version_operator] = "version_operator",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_spdx_license_identifier_token1] = aux_sym_spdx_license_identifier_token1,
  [sym_license_identifier] = sym_license_identifier,
  [anon_sym_pragma] = anon_sym_pragma,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_CARET] = anon_sym_CARET,
  [anon_sym_TILDE] = anon_sym_TILDE,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_version_literal] = sym_version_literal,
  [sym_identifier] = sym_identifier,
  [sym_source_file] = sym_source_file,
  [sym__top_level_element] = sym__top_level_element,
  [sym_spdx_license_identifier] = sym_spdx_license_identifier,
  [sym_pragma_directive] = sym_pragma_directive,
  [aux_sym__pragma_expression] = aux_sym__pragma_expression,
  [sym_version_constraint] = sym_version_constraint,
  [sym_version_operator] = sym_version_operator,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_spdx_license_identifier_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_license_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_pragma] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_version_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__top_level_element] = {
    .visible = false,
    .named = true,
  },
  [sym_spdx_license_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_pragma_directive] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__pragma_expression] = {
    .visible = false,
    .named = false,
  },
  [sym_version_constraint] = {
    .visible = true,
    .named = true,
  },
  [sym_version_operator] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_license = 1,
  field_name = 2,
  field_value = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_license] = "license",
  [field_name] = "name",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_license, 1},
  [1] =
    {field_name, 1},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(35);
      ADVANCE_MAP(
        '/', 3,
        ';', 39,
        '<', 45,
        '=', 46,
        '>', 44,
        '^', 40,
        'p', 27,
        '~', 41,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 1:
      if (lookahead == '-') ADVANCE(7);
      END_STATE();
    case 2:
      if (lookahead == '-') ADVANCE(6);
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(9);
      END_STATE();
    case 4:
      if (lookahead == ':') ADVANCE(36);
      END_STATE();
    case 5:
      if (lookahead == 'D') ADVANCE(10);
      END_STATE();
    case 6:
      if (lookahead == 'I') ADVANCE(14);
      END_STATE();
    case 7:
      if (lookahead == 'L') ADVANCE(21);
      END_STATE();
    case 8:
      if (lookahead == 'P') ADVANCE(5);
      END_STATE();
    case 9:
      if (lookahead == 'S') ADVANCE(8);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == 'X') ADVANCE(1);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(20);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(38);
      END_STATE();
    case 13:
      if (lookahead == 'c') ADVANCE(15);
      END_STATE();
    case 14:
      if (lookahead == 'd') ADVANCE(18);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(25);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(28);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(2);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(26);
      END_STATE();
    case 19:
      if (lookahead == 'f') ADVANCE(23);
      END_STATE();
    case 20:
      if (lookahead == 'g') ADVANCE(24);
      END_STATE();
    case 21:
      if (lookahead == 'i') ADVANCE(13);
      END_STATE();
    case 22:
      if (lookahead == 'i') ADVANCE(19);
      END_STATE();
    case 23:
      if (lookahead == 'i') ADVANCE(16);
      END_STATE();
    case 24:
      if (lookahead == 'm') ADVANCE(12);
      END_STATE();
    case 25:
      if (lookahead == 'n') ADVANCE(29);
      END_STATE();
    case 26:
      if (lookahead == 'n') ADVANCE(30);
      END_STATE();
    case 27:
      if (lookahead == 'r') ADVANCE(11);
      END_STATE();
    case 28:
      if (lookahead == 'r') ADVANCE(4);
      END_STATE();
    case 29:
      if (lookahead == 's') ADVANCE(17);
      END_STATE();
    case 30:
      if (lookahead == 't') ADVANCE(22);
      END_STATE();
    case 31:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(31);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 32:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(32);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 33:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(49);
      END_STATE();
    case 34:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_spdx_license_identifier_token1);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_license_identifier);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_pragma);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_TILDE);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(42);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(43);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_version_literal);
      if (lookahead == '.') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_version_literal);
      if (lookahead == '.') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_version_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 31},
  [12] = {.lex_state = 32},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_spdx_license_identifier_token1] = ACTIONS(1),
    [anon_sym_pragma] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [anon_sym_TILDE] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_version_literal] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(13),
    [sym__top_level_element] = STATE(7),
    [sym_spdx_license_identifier] = STATE(7),
    [sym_pragma_directive] = STATE(7),
    [aux_sym_source_file_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_spdx_license_identifier_token1] = ACTIONS(5),
    [anon_sym_pragma] = ACTIONS(7),
  },
  [STATE(2)] = {
    [aux_sym__pragma_expression] = STATE(3),
    [sym_version_constraint] = STATE(3),
    [sym_version_operator] = STATE(15),
    [anon_sym_SEMI] = ACTIONS(9),
    [anon_sym_CARET] = ACTIONS(11),
    [anon_sym_TILDE] = ACTIONS(11),
    [anon_sym_GT_EQ] = ACTIONS(11),
    [anon_sym_LT_EQ] = ACTIONS(11),
    [anon_sym_GT] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(13),
    [anon_sym_EQ] = ACTIONS(11),
    [sym_version_literal] = ACTIONS(15),
  },
  [STATE(3)] = {
    [aux_sym__pragma_expression] = STATE(3),
    [sym_version_constraint] = STATE(3),
    [sym_version_operator] = STATE(15),
    [anon_sym_SEMI] = ACTIONS(17),
    [anon_sym_CARET] = ACTIONS(19),
    [anon_sym_TILDE] = ACTIONS(19),
    [anon_sym_GT_EQ] = ACTIONS(19),
    [anon_sym_LT_EQ] = ACTIONS(19),
    [anon_sym_GT] = ACTIONS(22),
    [anon_sym_LT] = ACTIONS(22),
    [anon_sym_EQ] = ACTIONS(19),
    [sym_version_literal] = ACTIONS(25),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(15), 1,
      sym_version_literal,
    STATE(15), 1,
      sym_version_operator,
    ACTIONS(13), 2,
      anon_sym_GT,
      anon_sym_LT,
    STATE(2), 2,
      aux_sym__pragma_expression,
      sym_version_constraint,
    ACTIONS(11), 5,
      anon_sym_CARET,
      anon_sym_TILDE,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
  [22] = 2,
    ACTIONS(30), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(28), 7,
      anon_sym_SEMI,
      anon_sym_CARET,
      anon_sym_TILDE,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      sym_version_literal,
  [36] = 2,
    ACTIONS(34), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(32), 7,
      anon_sym_SEMI,
      anon_sym_CARET,
      anon_sym_TILDE,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      sym_version_literal,
  [50] = 4,
    ACTIONS(5), 1,
      aux_sym_spdx_license_identifier_token1,
    ACTIONS(7), 1,
      anon_sym_pragma,
    ACTIONS(36), 1,
      ts_builtin_sym_end,
    STATE(8), 4,
      sym__top_level_element,
      sym_spdx_license_identifier,
      sym_pragma_directive,
      aux_sym_source_file_repeat1,
  [66] = 4,
    ACTIONS(38), 1,
      ts_builtin_sym_end,
    ACTIONS(40), 1,
      aux_sym_spdx_license_identifier_token1,
    ACTIONS(43), 1,
      anon_sym_pragma,
    STATE(8), 4,
      sym__top_level_element,
      sym_spdx_license_identifier,
      sym_pragma_directive,
      aux_sym_source_file_repeat1,
  [82] = 1,
    ACTIONS(46), 3,
      ts_builtin_sym_end,
      aux_sym_spdx_license_identifier_token1,
      anon_sym_pragma,
  [88] = 1,
    ACTIONS(48), 3,
      ts_builtin_sym_end,
      aux_sym_spdx_license_identifier_token1,
      anon_sym_pragma,
  [94] = 1,
    ACTIONS(50), 1,
      sym_license_identifier,
  [98] = 1,
    ACTIONS(52), 1,
      sym_identifier,
  [102] = 1,
    ACTIONS(54), 1,
      ts_builtin_sym_end,
  [106] = 1,
    ACTIONS(56), 1,
      sym_version_literal,
  [110] = 1,
    ACTIONS(58), 1,
      sym_version_literal,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 22,
  [SMALL_STATE(6)] = 36,
  [SMALL_STATE(7)] = 50,
  [SMALL_STATE(8)] = 66,
  [SMALL_STATE(9)] = 82,
  [SMALL_STATE(10)] = 88,
  [SMALL_STATE(11)] = 94,
  [SMALL_STATE(12)] = 98,
  [SMALL_STATE(13)] = 102,
  [SMALL_STATE(14)] = 106,
  [SMALL_STATE(15)] = 110,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__pragma_expression, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__pragma_expression, 2, 0, 0), SHIFT_REPEAT(14),
  [22] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__pragma_expression, 2, 0, 0), SHIFT_REPEAT(14),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__pragma_expression, 2, 0, 0), SHIFT_REPEAT(5),
  [28] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_version_constraint, 1, 0, 0),
  [30] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_version_constraint, 1, 0, 0),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_version_constraint, 2, 0, 0),
  [34] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_version_constraint, 2, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_spdx_license_identifier, 2, 0, 1),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pragma_directive, 4, 0, 2),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [54] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_version_operator, 1, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_solidity(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "solidity",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
