/* Automatically @generated by tree-sitter v0.25.6 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 13
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 15
#define ALIAS_COUNT 0
#define TOKEN_COUNT 8
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_spdx_license_identifier_token1 = 1,
  sym_license_identifier = 2,
  anon_sym_pragma = 3,
  anon_sym_SEMI = 4,
  aux_sym__pragma_token_token1 = 5,
  aux_sym__pragma_token_token2 = 6,
  sym_identifier = 7,
  sym_source_file = 8,
  sym__top_level_element = 9,
  sym_spdx_license_identifier = 10,
  sym_pragma_directive = 11,
  sym__pragma_token = 12,
  aux_sym_source_file_repeat1 = 13,
  aux_sym_pragma_directive_repeat1 = 14,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_spdx_license_identifier_token1] = "spdx_license_identifier_token1",
  [sym_license_identifier] = "license_identifier",
  [anon_sym_pragma] = "pragma",
  [anon_sym_SEMI] = ";",
  [aux_sym__pragma_token_token1] = "_pragma_token_token1",
  [aux_sym__pragma_token_token2] = "_pragma_token_token2",
  [sym_identifier] = "identifier",
  [sym_source_file] = "source_file",
  [sym__top_level_element] = "_top_level_element",
  [sym_spdx_license_identifier] = "spdx_license_identifier",
  [sym_pragma_directive] = "pragma_directive",
  [sym__pragma_token] = "_pragma_token",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_pragma_directive_repeat1] = "pragma_directive_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_spdx_license_identifier_token1] = aux_sym_spdx_license_identifier_token1,
  [sym_license_identifier] = sym_license_identifier,
  [anon_sym_pragma] = anon_sym_pragma,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [aux_sym__pragma_token_token1] = aux_sym__pragma_token_token1,
  [aux_sym__pragma_token_token2] = aux_sym__pragma_token_token2,
  [sym_identifier] = sym_identifier,
  [sym_source_file] = sym_source_file,
  [sym__top_level_element] = sym__top_level_element,
  [sym_spdx_license_identifier] = sym_spdx_license_identifier,
  [sym_pragma_directive] = sym_pragma_directive,
  [sym__pragma_token] = sym__pragma_token,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_pragma_directive_repeat1] = aux_sym_pragma_directive_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_spdx_license_identifier_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_license_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_pragma] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__pragma_token_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__pragma_token_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__top_level_element] = {
    .visible = false,
    .named = true,
  },
  [sym_spdx_license_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_pragma_directive] = {
    .visible = true,
    .named = true,
  },
  [sym__pragma_token] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pragma_directive_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_license = 1,
  field_name = 2,
  field_value = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_license] = "license",
  [field_name] = "name",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_license, 1},
  [1] =
    {field_name, 1},
  [2] =
    {field_name, 1},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(33);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == ';') ADVANCE(37);
      if (lookahead == 'p') ADVANCE(28);
      if (('<' <= lookahead && lookahead <= '>') ||
          lookahead == '^' ||
          lookahead == '~') ADVANCE(39);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('.' <= lookahead && lookahead <= '9')) ADVANCE(38);
      END_STATE();
    case 1:
      if (lookahead == '-') ADVANCE(8);
      END_STATE();
    case 2:
      if (lookahead == '-') ADVANCE(7);
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(10);
      END_STATE();
    case 4:
      if (lookahead == ':') ADVANCE(34);
      END_STATE();
    case 5:
      if (lookahead == ';') ADVANCE(37);
      if (('<' <= lookahead && lookahead <= '>') ||
          lookahead == '^' ||
          lookahead == '~') ADVANCE(39);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 6:
      if (lookahead == 'D') ADVANCE(11);
      END_STATE();
    case 7:
      if (lookahead == 'I') ADVANCE(15);
      END_STATE();
    case 8:
      if (lookahead == 'L') ADVANCE(22);
      END_STATE();
    case 9:
      if (lookahead == 'P') ADVANCE(6);
      END_STATE();
    case 10:
      if (lookahead == 'S') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(10);
      END_STATE();
    case 11:
      if (lookahead == 'X') ADVANCE(1);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(21);
      END_STATE();
    case 13:
      if (lookahead == 'a') ADVANCE(36);
      END_STATE();
    case 14:
      if (lookahead == 'c') ADVANCE(16);
      END_STATE();
    case 15:
      if (lookahead == 'd') ADVANCE(19);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(26);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(29);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(2);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(27);
      END_STATE();
    case 20:
      if (lookahead == 'f') ADVANCE(24);
      END_STATE();
    case 21:
      if (lookahead == 'g') ADVANCE(25);
      END_STATE();
    case 22:
      if (lookahead == 'i') ADVANCE(14);
      END_STATE();
    case 23:
      if (lookahead == 'i') ADVANCE(20);
      END_STATE();
    case 24:
      if (lookahead == 'i') ADVANCE(17);
      END_STATE();
    case 25:
      if (lookahead == 'm') ADVANCE(13);
      END_STATE();
    case 26:
      if (lookahead == 'n') ADVANCE(30);
      END_STATE();
    case 27:
      if (lookahead == 'n') ADVANCE(31);
      END_STATE();
    case 28:
      if (lookahead == 'r') ADVANCE(12);
      END_STATE();
    case 29:
      if (lookahead == 'r') ADVANCE(4);
      END_STATE();
    case 30:
      if (lookahead == 's') ADVANCE(18);
      END_STATE();
    case 31:
      if (lookahead == 't') ADVANCE(23);
      END_STATE();
    case 32:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(32);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_spdx_license_identifier_token1);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_license_identifier);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_pragma);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym__pragma_token_token1);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym__pragma_token_token2);
      if (('<' <= lookahead && lookahead <= '>') ||
          lookahead == '^' ||
          lookahead == '~') ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 5},
  [5] = {.lex_state = 5},
  [6] = {.lex_state = 5},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 32},
  [11] = {.lex_state = 5},
  [12] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_spdx_license_identifier_token1] = ACTIONS(1),
    [anon_sym_pragma] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [aux_sym__pragma_token_token1] = ACTIONS(1),
    [aux_sym__pragma_token_token2] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(12),
    [sym__top_level_element] = STATE(2),
    [sym_spdx_license_identifier] = STATE(2),
    [sym_pragma_directive] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_spdx_license_identifier_token1] = ACTIONS(5),
    [anon_sym_pragma] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(5), 1,
      aux_sym_spdx_license_identifier_token1,
    ACTIONS(7), 1,
      anon_sym_pragma,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    STATE(3), 4,
      sym__top_level_element,
      sym_spdx_license_identifier,
      sym_pragma_directive,
      aux_sym_source_file_repeat1,
  [16] = 4,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    ACTIONS(13), 1,
      aux_sym_spdx_license_identifier_token1,
    ACTIONS(16), 1,
      anon_sym_pragma,
    STATE(3), 4,
      sym__top_level_element,
      sym_spdx_license_identifier,
      sym_pragma_directive,
      aux_sym_source_file_repeat1,
  [32] = 3,
    ACTIONS(19), 1,
      anon_sym_SEMI,
    STATE(5), 2,
      sym__pragma_token,
      aux_sym_pragma_directive_repeat1,
    ACTIONS(21), 3,
      aux_sym__pragma_token_token1,
      aux_sym__pragma_token_token2,
      sym_identifier,
  [45] = 3,
    ACTIONS(23), 1,
      anon_sym_SEMI,
    STATE(6), 2,
      sym__pragma_token,
      aux_sym_pragma_directive_repeat1,
    ACTIONS(25), 3,
      aux_sym__pragma_token_token1,
      aux_sym__pragma_token_token2,
      sym_identifier,
  [58] = 3,
    ACTIONS(27), 1,
      anon_sym_SEMI,
    STATE(6), 2,
      sym__pragma_token,
      aux_sym_pragma_directive_repeat1,
    ACTIONS(29), 3,
      aux_sym__pragma_token_token1,
      aux_sym__pragma_token_token2,
      sym_identifier,
  [71] = 1,
    ACTIONS(32), 3,
      ts_builtin_sym_end,
      aux_sym_spdx_license_identifier_token1,
      anon_sym_pragma,
  [77] = 1,
    ACTIONS(34), 3,
      ts_builtin_sym_end,
      aux_sym_spdx_license_identifier_token1,
      anon_sym_pragma,
  [83] = 1,
    ACTIONS(36), 3,
      ts_builtin_sym_end,
      aux_sym_spdx_license_identifier_token1,
      anon_sym_pragma,
  [89] = 1,
    ACTIONS(38), 1,
      sym_license_identifier,
  [93] = 1,
    ACTIONS(40), 1,
      sym_identifier,
  [97] = 1,
    ACTIONS(42), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 16,
  [SMALL_STATE(4)] = 32,
  [SMALL_STATE(5)] = 45,
  [SMALL_STATE(6)] = 58,
  [SMALL_STATE(7)] = 71,
  [SMALL_STATE(8)] = 77,
  [SMALL_STATE(9)] = 83,
  [SMALL_STATE(10)] = 89,
  [SMALL_STATE(11)] = 93,
  [SMALL_STATE(12)] = 97,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [13] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [16] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pragma_directive_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pragma_directive_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_spdx_license_identifier, 2, 0, 1),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pragma_directive, 3, 0, 2),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pragma_directive, 4, 0, 3),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [42] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_solidity(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "solidity",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
